apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-appset
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/mdesousa-dev/argocd.git
      revision: HEAD
      directories:
      - path: apps/*/envs/dev   
  template:    
    metadata:
      name: '{{index .path.segments 1}}-{{index .path.segments 3}}'
      labels:
        env: '{{index .path.segments 3}}'   
    spec:
      # The project the application belongs to.
      project: default

      # Source of the application manifests
      source:
        repoURL: https://github.com/mdesousa-dev/argocd.git
        targetRevision: HEAD
        path: '{{.path.path}}'
        helm: 
          valueFiles: 
            - ../../base/default.values.yaml
      
      # Destination cluster and namespace to deploy the application
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{index .path.segments 1}}-{{index .path.segments 3}}'

      syncPolicy:
        syncOptions:
        - CreateNamespace=true
